import { Tournament } from '../types/tournament';
import { generateRoundRobinFixture } from './fixtureGenerator';

export const SAMPLE_TOURNAMENT: Tournament = {
  id: 'torneo_recreo_3b_2026',
  name: 'Copa Relámpago Recreo 3°B',
  organizer: 'Comité Deportivo 3° Año B',
  section: '3.er año · Desarrollo de Software «B»',
  matchDurationMinutes: 15,
  createdAt: '2026-10-01T07:15:00.000Z',
  updatedAt: '2026-10-01T08:30:00.000Z',
  teams: [
    {
      id: 'team_rayos',
      name: 'Los Rayos 3°B',
      captain: 'Carlos Gómez',
      color: '#06b6d4', // Cyan
      emoji: '⚡',
      yellowCards: 1,
      redCards: 0,
      createdAt: '2026-10-01T07:15:00.000Z',
      players: [
        { id: 'p1', name: 'Carlos Gómez', number: 10, position: 'Delantero' },
        { id: 'p2', name: 'Mateo Rivas', number: 1, position: 'Portero' },
        { id: 'p3', name: 'Alejandro Cruz', number: 4, position: 'Defensa' },
        { id: 'p4', name: 'Bryan Soto', number: 8, position: 'Medio' },
        { id: 'p5', name: 'Diego Henríquez', number: 7, position: 'Delantero' },
      ],
    },
    {
      id: 'team_furia',
      name: 'Furia Roja FC',
      captain: 'Kevin Morales',
      color: '#ef4444', // Red
      emoji: '🔥',
      yellowCards: 2,
      redCards: 0,
      createdAt: '2026-10-01T07:16:00.000Z',
      players: [
        { id: 'p6', name: 'Kevin Morales', number: 9, position: 'Delantero' },
        { id: 'p7', name: 'Luis Fernando', number: 12, position: 'Portero' },
        { id: 'p8', name: 'Josué Alvarado', number: 3, position: 'Defensa' },
        { id: 'p9', name: 'Samuel Ramos', number: 5, position: 'Medio' },
        { id: 'p10', name: 'Emerson Peña', number: 11, position: 'Delantero' },
      ],
    },
    {
      id: 'team_halcones',
      name: 'Halcones Dorados',
      captain: 'Rodrigo Flores',
      color: '#f59e0b', // Amber
      emoji: '🦅',
      yellowCards: 0,
      redCards: 0,
      createdAt: '2026-10-01T07:18:00.000Z',
      players: [
        { id: 'p11', name: 'Rodrigo Flores', number: 7, position: 'Medio' },
        { id: 'p12', name: 'Nelson Lemus', number: 1, position: 'Portero' },
        { id: 'p13', name: 'Jonathan Meza', number: 2, position: 'Defensa' },
        { id: 'p14', name: 'Wilmer Ayala', number: 6, position: 'Medio' },
        { id: 'p15', name: 'Gabriel Torres', number: 10, position: 'Delantero' },
      ],
    },
    {
      id: 'team_depor',
      name: 'Deportivo Bachilleres',
      captain: 'Andrea Castillo',
      color: '#10b981', // Emerald
      emoji: '⚽',
      yellowCards: 1,
      redCards: 0,
      createdAt: '2026-10-01T07:20:00.000Z',
      players: [
        { id: 'p16', name: 'Andrea Castillo', number: 5, position: 'Medio' },
        { id: 'p17', name: 'Manuel Estrada', number: 22, position: 'Portero' },
        { id: 'p18', name: 'Christian Silva', number: 4, position: 'Defensa' },
        { id: 'p19', name: 'David Menjívar', number: 8, position: 'Medio' },
        { id: 'p20', name: 'Víctor Guardado', number: 11, position: 'Delantero' },
      ],
    },
  ],
  matches: [
    // Fecha 1
    {
      id: 'match_r1_m1',
      round: 1,
      homeTeamId: 'team_rayos',
      awayTeamId: 'team_depor',
      homeTeamName: 'Los Rayos 3°B',
      awayTeamName: 'Deportivo Bachilleres',
      homeScore: 3,
      awayScore: 1,
      status: 'finished',
      homeYellowCards: 0,
      awayYellowCards: 1,
      playedAt: '2026-10-01T07:30:00.000Z',
      notes: 'Partidazo inaugural del recreo matutino.',
    },
    {
      id: 'match_r1_m2',
      round: 1,
      homeTeamId: 'team_furia',
      awayTeamId: 'team_halcones',
      homeTeamName: 'Furia Roja FC',
      awayTeamName: 'Halcones Dorados',
      homeScore: 2,
      awayScore: 2,
      status: 'finished',
      homeYellowCards: 1,
      awayYellowCards: 0,
      playedAt: '2026-10-01T07:50:00.000Z',
      notes: 'Empate electrizante en el último minuto.',
    },
    // Fecha 2
    {
      id: 'match_r2_m1',
      round: 2,
      homeTeamId: 'team_rayos',
      awayTeamId: 'team_halcones',
      homeTeamName: 'Los Rayos 3°B',
      awayTeamName: 'Halcones Dorados',
      homeScore: 1,
      awayScore: 2,
      status: 'finished',
      homeYellowCards: 1,
      awayYellowCards: 0,
      playedAt: '2026-10-01T08:10:00.000Z',
      notes: 'Sorpresa de Halcones con gol de tiro libre.',
    },
    {
      id: 'match_r2_m2',
      round: 2,
      homeTeamId: 'team_furia',
      awayTeamId: 'team_depor',
      homeTeamName: 'Furia Roja FC',
      awayTeamName: 'Deportivo Bachilleres',
      homeScore: 4,
      awayScore: 1,
      status: 'finished',
      homeYellowCards: 1,
      awayYellowCards: 0,
      playedAt: '2026-10-01T08:30:00.000Z',
      notes: 'Gran despliegue ofensivo de Furia Roja.',
    },
    // Fecha 3 (Pendientes para la gran definición del recreo)
    {
      id: 'match_r3_m1',
      round: 3,
      homeTeamId: 'team_rayos',
      awayTeamId: 'team_furia',
      homeTeamName: 'Los Rayos 3°B',
      awayTeamName: 'Furia Roja FC',
      homeScore: 0,
      awayScore: 0,
      status: 'pending',
      homeYellowCards: 0,
      awayYellowCards: 0,
      notes: 'Clásico decisivo por el liderato.',
    },
    {
      id: 'match_r3_m2',
      round: 3,
      homeTeamId: 'team_halcones',
      awayTeamId: 'team_depor',
      homeTeamName: 'Halcones Dorados',
      awayTeamName: 'Deportivo Bachilleres',
      homeScore: 0,
      awayScore: 0,
      status: 'pending',
      homeYellowCards: 0,
      awayYellowCards: 0,
      notes: 'Halcones busca asegurar podio.',
    },
  ],
};
